kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: swiki
      POSTGRES_DB: swiki
      POSTGRES_PASSWORD: abc123

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./target
        - ./cargo-home

  - name: migrate and test
    image: rust:1
    environment:
      CARGO_HOME: ./cargo-home
      DATABASE_URL: postgres://swiki:abc123@postgres:5432/swiki
      ROCKET_DATABASE_URL: postgres://swiki:abc123@postgres:5432/swiki
    commands:
      - cargo install sqlx-cli --no-default-features --features postgres
      - cargo sqlx migrate run
      - cargo test

  - name: rebuild cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./target
        - ./cargo-home

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: bot_token
      to: -1001423060188
    when:
      branch:
        - main
      event:
        - push

volumes:
  - name: cache
    host:
      path: /tmp/cache
