kind: pipeline
type: docker
name: default

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./target
        - ./cargo-home

  - name: test
    image: rust:1.49-slim-buster
    environment:
      CARGO_HOME: ./cargo-home
    commands:
      - cargo test

  - name: rebuild cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./target
        - ./cargo-home

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: bot_token
      to: -1001423060188
    when:
      branch:
        - main
      event:
        - push

volumes:
  - name: cache
    host:
      path: /tmp/cache
